# Generated by Django 5.2.8 on 2025-11-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "case_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "psu",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "side_panel",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "external_volume",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "internal_35_bays",
                    models.IntegerField(blank=True, null=True),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "socket",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("core_count", models.IntegerField(blank=True, null=True)),
                (
                    "core_clock",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "boost_clock",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "microarchitecture",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("tdp", models.IntegerField(blank=True, null=True)),
                (
                    "graphics",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("thread_count", models.IntegerField(blank=True, null=True)),
                (
                    "userbenchmark_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "blender_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "power_consumption_overclocked",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CPUCooler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("rpm", models.IntegerField(blank=True, null=True)),
                (
                    "noise_level",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "size",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("liquid", models.BooleanField(blank=True, null=True)),
                (
                    "power_throughput",
                    models.IntegerField(blank=True, null=True),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="GPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gpu_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "userbenchmark_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("userbenchmark_url", models.URLField(blank=True, null=True)),
                (
                    "blender_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                (
                    "generation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "base_clock",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "boost_clock",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "architecture",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("process_size", models.IntegerField(blank=True, null=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "bus_interface",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "memory_clock",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("memory_size_gb", models.IntegerField(blank=True, null=True)),
                (
                    "memory_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("shading_units", models.IntegerField(blank=True, null=True)),
                ("tmus", models.IntegerField(blank=True, null=True)),
                ("rops", models.IntegerField(blank=True, null=True)),
                ("sms", models.IntegerField(blank=True, null=True)),
                ("tensor_cores", models.IntegerField(blank=True, null=True)),
                ("rt_cores", models.IntegerField(blank=True, null=True)),
                ("l1_cache_kb", models.IntegerField(blank=True, null=True)),
                (
                    "l2_cache_mb",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("tdp", models.IntegerField(blank=True, null=True)),
                (
                    "board_length",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "board_width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "slot_width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "suggested_psu",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "power_connectors",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "display_connectors",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Motherboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "socket",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "form_factor",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("max_memory", models.IntegerField(blank=True, null=True)),
                ("memory_slots", models.IntegerField(blank=True, null=True)),
                (
                    "color",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "ddr_version",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "ddr_max_speed",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "nvme_support",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "bios_update_required",
                    models.BooleanField(blank=True, null=True),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="PSU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "psu_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "efficiency",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "wattage",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "modular",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "color",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="RAM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("modules", models.IntegerField(blank=True, null=True)),
                (
                    "color",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "first_word_latency",
                    models.IntegerField(blank=True, null=True),
                ),
                ("cas_latency", models.IntegerField(blank=True, null=True)),
                (
                    "ddr_generation",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("frequency_mhz", models.IntegerField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
                ("capacity_gb", models.IntegerField(blank=True, null=True)),
                (
                    "benchmark",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("capacity", models.IntegerField(blank=True, null=True)),
                (
                    "storage_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("cache", models.IntegerField(blank=True, null=True)),
                (
                    "form_factor",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "interface",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ThermalPaste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
            ],
        ),
    ]
