# Generated by Django 5.2.8 on 2025-11-29 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0005_alter_case_case_type_alter_case_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="case_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="external_volume",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="psu",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="case",
            name="side_panel",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
