# Generated by Django 5.2.8 on 2025-11-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardware", "0009_alter_psu_color_alter_psu_efficiency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storage",
            name="form_factor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="storage",
            name="interface",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="storage",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="storage",
            name="storage_type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
