# Generated by Django 5.2.8 on 2025-12-01 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0010_alter_storage_form_factor_alter_storage_interface_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermalpaste',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
