# Generated by Django 5.2.8 on 2025-12-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0011_alter_thermalpaste_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
