# Generated by Django 5.2.8 on 2025-12-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_currencyrate_userbuild_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuild',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userbuild',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
