# Generated by Django 5.2.8 on 2025-12-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculator",
            "0005_userbuild_bottleneck_pct_userbuild_bottleneck_type_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userbuild",
            name="is_upgrade",
            field=models.BooleanField(default=False),
        ),
    ]
