# Generated by Django 5.2.8 on 2025-12-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_userbuild_is_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuild',
            name='upgrade_base',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
